#!/bin/bash

# Script for updating data.  After pulling and merging, it will
# regenerate the history & update the notebooks.

# Setup:
#   After cloning, link in the forked source:
#      git remote add owid https://github.com/owid/covid-19-data.git

# Then, to update, first, pull and merge latest data first, as in:
#    git fetch --all -p
#    git merge owid/master

# Then run this script to extract the history and update the notebooks

# Clear out previous datasets
rm all_versions_exported/*

# Pull history
scripts/scripts/git-export-all-file-versions public/data/owid-covid-data.csv

# Generate history.csv file:
python scripts/scripts/generate-history.py

# Update Analysis:

jupyter nbconvert --to notebook --inplace --execute scripts/notebooks/Analysis.ipynb

# Update Growth:

# jupyter nbconvert --to notebook --inplace --execute scripts/notebooks/Growth.ipynb

# Update graphs for slides:

jupyter nbconvert --to notebook --inplace --execute scripts/notebooks/TalkSlides.ipynb
